#include "shell.h"

/*
** This function catches the signal SIGCHLD that is generated by each child
** process launched within the function `launch_job`.
** SIGCHLD is received when a process:
** - has terminated
** - is stopped by receiving the signal SIGTSTP
** This function does:
** - save the status of the process (completed or stopped)
** - check the status of the whole job
** - notify the user if the job is completed or stopped
** - free the job when completed
*/

static void	s_job_notification (void)
{
	t_job	*j;
	t_job	*j_next;

	j = g_current_jobs;
	while (j)
	{
		j_next = j->next;
		if (job_is_completed(j) == 1)
		{
			// check if it is a background job
			// and warn user about its status
			//if (is_job_stopped(j) == 1 || j->foreground == 0)
			//{
			//	display a message "job completed"
			//	reinit_prompt();
			//}

			// remove job from list of current jobs
			if (j->prev)
				j->prev->next = j->next;
			else
				g_current_jobs = j->next;
			if (j->next)
				j->next->prev = j->prev;
		}
		// else Ctrl + Z
		//else if (is_job_stopped(j) == 1 && j->notified == 0)
		//{
		//	format_job_info (j, "stopped");
		//	j->notified = 1;
		//}

		j = j_next;
	}
}

void	signal_sigchld(int sig)
{
	int		status;
	pid_t	pid;

	log_debug("SIGCHLD received\n");
	if (sig == SIGCHLD)
	{
		errno = 0;
		while (1)
		{
			pid = waitpid(WAIT_ANY, &status, WUNTRACED | WNOHANG);
			if (proc_update_status(pid, status) == 0)
				break ;
		}
		s_job_notification();
	}
}
